---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: "{{ namespace }}"
  labels:
    app: mysql
spec:
  type: LoadBalancer
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app: mysql
...
