---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: "{{ namespace }}"
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: "remove-lost-found"
          image: "busybox:1.29.3"
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
          command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      containers:
      - name: mysql
        image: "mysql:{{ mysqlVersion }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 1000m
            memory: 2048Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysqlRootPassword
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysqlPassword
        - name: MYSQL_USER
          value: "{{ mysqlUsername }}"
        - name: MYSQL_DATABASE
          value: "{{ matDbName }}"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "false"
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d
        - name: config-volume
          mountPath: /etc/my.cnf
          subPath: my.cnf
      volumes:
      - name: migrations
        configMap:
          name: mysql-initialization
      - name: data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: config-volume
        configMap:
          name: mysql-config
          optional: true
...
