---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: "{{ namespace }}"
type: Opaque
stringData:
  mysqlRootPassword: "{{ mysqlRootPassword }}"
  mysqlPassword: "{{ mysqlPassword }}"
...
