---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: "{{ namespace }}"
  labels:
    app: "elasticsearch"
  annotations:
    {}
spec:
  type: LoadBalancer
  selector:
    app: "elasticsearch"
  ports:
    - name: http
      protocol: TCP
      port: 9200
    - name: transport
      protocol: TCP
      port: 9300
...
