---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: "{{ namespace }}"
  name: istio-init-crd-10-latest
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-init-service-account
      containers:
        - name: istio-init-crd-10
          image: "gcr.io/istio-testing/kubectl:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: crd-10
              mountPath: /etc/istio/crd-10
              readOnly: true
          command: ["kubectl",  "apply", "-f", "/etc/istio/crd-10/crd-10.yaml"]
      volumes:
        - name: crd-10
          configMap:
            name: istio-crd-10
      restartPolicy: OnFailure
...
