---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ namespace }}"
  name: istio-crd-12
data:
  crd-12.yaml: |-
    kind: CustomResourceDefinition
    apiVersion: apiextensions.k8s.io/v1beta1
    metadata:
      name: authorizationpolicies.rbac.istio.io
      labels:
        app: istio-pilot
        istio: rbac
        heritage: Tiller
        release: istio
    spec:
      group: rbac.istio.io
      names:
        kind: AuthorizationPolicy
        plural: authorizationpolicies
        singular: authorizationpolicy
        categories:
          - istio-io
          - rbac-istio-io
      scope: Namespaced
      versions:
        - name: v1alpha1
          served: true
          storage: true
    ---
...
