---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: "{{ namespace }}"
  labels:
    app: kibana
    release: "kibana"
spec:
  type: ClusterIP
  ports:
    - port: 5601
      protocol: TCP
      name: http
      targetPort: 5601
  selector:
    app: kibana
    release: "kibana"
...
