---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-fluentd-elasticsearch
  namespace: "{{ namespace }}"
  labels:
    app.kubernetes.io/name: fluentd-elasticsearch
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/version: "2.7.0"
    app.kubernetes.io/managed-by: Ansible
subjects:
  - kind: ServiceAccount
    name: fluentd-fluentd-elasticsearch
    namespace: default
roleRef:
  kind: ClusterRole
  name: fluentd-fluentd-elasticsearch
  apiGroup: rbac.authorization.k8s.io
...
