---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-fluentd-elasticsearch
  namespace: "{{ namespace }}"
  labels:
    app.kubernetes.io/name: fluentd-elasticsearch
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/version: "2.7.0"
    app.kubernetes.io/managed-by: Ansible
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
...
