---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-fluentd-elasticsearch
  namespace: "{{ namespace }}"
  labels:
    app.kubernetes.io/name: fluentd-elasticsearch
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/managed-by: Ansible
...
