---
- name: Remove the Kibana Kubernetes Service
  k8s:
    state: absent
    api_version: v1
    kind: Service
    namespace: "{{ namespace }}"
    name: kibana

- name: Remove the Kibana Kubernetes Deployment
  k8s:
    state: absent
    api_version: v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: kibana
...
