---
apiVersion: v1
kind: Service
metadata:
  name: measure-authoring-tool-service
  namespace: "{{ namespace }}"
  labels:
    app: measure-authoring-tool
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: measure-authoring-tool
...
