---
- name: Create a the {{ namespace }} namespace
  k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- set_fact:
    chart_name: metrics-server
    chart_repo: stable/metrics-server
    chart_var_file: "{{ role_path }}/files/values.yml"
    chart_overrides: "{{ metrics_chart_overrides }}"
    helm_flags: "{{ metrics_helm_flags }}"

- import_role:
    name: "{{ role_path }}/../helm"
...
