---
- name: Create the Kubernetes resources using helm template
  vars:
    overrides: "
    {% if chart_overrides is not none %}
        {% for key, value in chart_overrides.iteritems() %}
          --set {{ key }}={{ value }}
          {% if not loop.last %} {% endif %}
      {% endfor %}
    {% endif %}"
  command: helm template {{ chart_name }} {{ chart_repo }} -f {{ chart_var_file }} {{ overrides }}
  register: k8s_template_raw
  changed_when: false

#- debug:
#    msg: '{{ item }}'
#  loop: '{{ k8s_template_raw.stdout | from_yaml_all | list }}'

- name: "{{ 'Deploy' if chart_state == 'present' else 'Remove' }} the Kubernetes artifacts"
  vars:
    template_yaml: "{{ k8s_template_raw.stdout | from_yaml_all | list }}"
  k8s:
    state: "{{ chart_state }}"
    namespace: "{{ namespace }}"
    definition: "{{ template_yaml }}"
...
