apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::498284886784:role/BMAT-dev-worker-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - userarn: arn:aws:iam::498284886784:user/andrew.bird
      username: andrew.bird
      groups:
        - system:masters

  
  
  
