podTemplate(containers: [
    containerTemplate(name: 'ansible', image: 'ansible/ansible-runner', ttyEnabled: true, command: 'cat'),
 ]) {

    node(POD_LABEL) {
        stage('Run ansible-playbook') {
            container('ansible') {
                    sh 'env'
                    sh 'yum install python2-openshift.noarch -y'
                    sh 'yum install python2-kubernetes.noarch -y'
                    ansiblePlaybook(playbook: '${params.PLAYBOOK}', vaultCredentialsId:'ansible-vault')
            }
        }
    }
}

